### ISSUE TITLE
error when cropping EXR

### ISSUE THREAD

**Issue by alijafargholi** [alijafargholi/image_utils#7]
Getting this error when trying to crop:

### Code

```python
from image_utils.image import Read
from image_utils.transform import crop_by_data_window

# read an image
source_image = Read(r"foo.exr")
# crop the source image and store it in a new variable
bar = crop_by_data_window(source_image)
```

### Error
```bash
Traceback (most recent call last):
  File "U:/ajafargholi/APPS_SANDBOX/image_utils/foo.py", line 10, in <module>
    bar = crop_by_data_window(source_image)
  File "U:\ajafargholi\APPS_SANDBOX\image_utils\image_utils\transform.py", line 75, in crop_by_data_window
    return crop(source_image, *source_image.data_window_coordinate)
  File "U:\ajafargholi\APPS_SANDBOX\image_utils\image_utils\transform.py", line 53, in crop
    pixel_type=source_image.pixeltype)
  File "U:\ajafargholi\APPS_SANDBOX\image_utils\image_utils\image.py", line 106, in __init__
    for attr_name, attr_value in getattr(extention, self.file_format).items():
AttributeError: 'module' object has no attribute ''
```

**Comment by alijafargholi** [comment]
It seems this issue is because of missing file extension in [here](https://github.com/alijafargholi/image_utils/blob/master/image_utils/image.py#L106)

#### solution:

```python
        if self.file_format:
            image_extension_attr = getattr(extention, self.file_format).items()
            for attr_name, attr_value in image_extension_attr:
                image_attr_value = self.spec().getattribute(attr_value)
                setattr(self, attr_name, image_attr_value)
```
